#!/bin/sh

#This file is part of CBCJVM.
#CBCJVM is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#CBCJVM is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with CBCJVM.  If not, see <http://www.gnu.org/licenses/>.

#Author: Braden McDorman

echo "[INSTALL] ----------------------------- [INSTALL]"
echo "[INSTALL] Destroying previous installation... "
rm -Rf /mnt/user/jvm
rm -f /mnt/user/lib/classes.zip /mnt/user/lib/glibj.zip /mnt/user/lib/libjavaio.so /mnt/user/lib/libjavalangreflect.so /mnt/user/lib/libjavalang.so /mnt/user/lib/libjavanet.so /mnt/user/lib/libjavanio.so /mnt/user/lib/libjavautil.so /mnt/user/lib/tools.zip
echo "[INSTALL] Copying Installer..."
cp /mnt/browser/usb/install_script_p2 /mnt/user
cp -R /mnt/browser/usb/install_data/* /mnt/user
echo "[INSTALL] Remove Drive. Press A to Continue."
