#!/bin/sh

#This file is part of CBCJVM.
#CBCJVM is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#CBCJVM is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with CBCJVM.  If not, see <http://www.gnu.org/licenses/>.

#Author: Braden McDorman

echo "[INSTALL] Compiling CBC Wrapper..."
cd /mnt/user/jvm/cbc/jni/
sh ./compile
cp ./CBC.so /mnt/user/jvm/cbc/
cd /mnt/user
echo "[INSTALL] Removing JNI source..."
rm -Rf /mnt/user/jvm/cbc/jni
echo "[INSTALL] Remounting and copying compile script."
cd /mnt/user/compile
mount -o remount,rw /dev/sda2
cp compile /mnt/kiss/usercode/
cd /mnt/user
rm -Rf compile
echo "[INSTALL] CBCJVM Installed!"
echo "Please run the HelloWorld Program to verify."
