/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbc_Motor */

#ifndef _Included_cbc_Motor
#define _Included_cbc_Motor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbc_Motor
 * Method:    motor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbc_Motor_motor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    clear_motor_position_counter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_clear_1motor_1position_1counter
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    move_at_velocity
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_move_1at_1velocity
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    mav
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_mav
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    move_to_position
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_move_1to_1position
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    mtp
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_mtp
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    move_relative_position
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_move_1relative_1position
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    mrp
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_mrp
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    set_pid_gains
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_cbc_Motor_set_1pid_1gains
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    freeze
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_freeze
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    get_motor_done
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_get_1motor_1done
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    get_motor_position_counter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_get_1motor_1position_1counter
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    block_motor_done
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_Motor_block_1motor_1done
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    bmd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_Motor_bmd
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    setpwm
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_setpwm
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_Motor
 * Method:    getpwm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cbc_Motor_getpwm
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    fd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_Motor_fd
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    bk
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_Motor_bk
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    off
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbc_Motor_off
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbc_Motor
 * Method:    ao
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_Motor_ao
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
