/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbc_Display */

#ifndef _Included_cbc_Display
#define _Included_cbc_Display
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbc_Display
 * Method:    display_clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_Display_display_1clear
  (JNIEnv *, jobject);

/*
 * Class:     cbc_Display
 * Method:    cbc_display_clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_Display_cbc_1display_1clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
