/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbc_Sound */

#ifndef _Included_cbc_Sound
#define _Included_cbc_Sound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbc_Sound
 * Method:    tone
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbc_Sound_tone
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbc_Sound
 * Method:    beep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbc_Sound_beep
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
