/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbc_Input */

#ifndef _Included_cbc_Input
#define _Included_cbc_Input
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbc_Input
 * Method:    up_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Input_up_1button
  (JNIEnv *, jobject);

/*
 * Class:     cbc_Input
 * Method:    down_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Input_down_1button
  (JNIEnv *, jobject);

/*
 * Class:     cbc_Input
 * Method:    left_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Input_left_1button
  (JNIEnv *, jobject);

/*
 * Class:     cbc_Input
 * Method:    right_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Input_right_1button
  (JNIEnv *, jobject);

/*
 * Class:     cbc_Input
 * Method:    a_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Input_a_1button
  (JNIEnv *, jobject);

/*
 * Class:     cbc_Input
 * Method:    b_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Input_b_1button
  (JNIEnv *, jobject);

/*
 * Class:     cbc_Input
 * Method:    black_button
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Input_black_1button
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
