/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __cbccore_low_Sound__
#define __cbccore_low_Sound__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_cbccore_low_Sound_tone (JNIEnv *env, jobject, jint, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Sound_beep (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __cbccore_low_Sound__ */
