/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __cbccore_low_Create__
#define __cbccore_low_Create__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1connect (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1disconnect (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1start (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1passive (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1safe (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1full (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spot (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1cover (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1demo (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1cover_1dock (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1mode (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1sensor_1update (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1wall (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1buttons (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1bumpdrop (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1cliffs (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1angle (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1distance (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1velocity (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1read_1IR (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1overcurrents (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1battery_1charge (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1cargo_1bay_1inputs (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1stop (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive (JNIEnv *env, jobject, jint, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive_1straight (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spin_1CW (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spin_1CCW (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive_1direct (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1spin_1block (JNIEnv *env, jobject, jint, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1advance_1led (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1play_1led (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1power_1led (JNIEnv *env, jobject, jint, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1digital_1output (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1pwm_1low_1side_1drivers (JNIEnv *env, jobject, jint, jint, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1low_1side_1drivers (JNIEnv *env, jobject, jint, jint, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1load_1song (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1play_1song (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1write_1byte (JNIEnv *env, jobject, jchar);
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1clear_1serial_1buffer (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __cbccore_low_Create__ */
