/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __cbccore_low_Servo__
#define __cbccore_low_Servo__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_cbccore_low_Servo_enable_1servos (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Servo_disable_1servos (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Servo_set_1servo_1position (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Servo_get_1servo_1position (JNIEnv *env, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif /* __cbccore_low_Servo__ */
