/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __cbccore_low_Device__
#define __cbccore_low_Device__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jfloat JNICALL Java_cbccore_low_Device_power_1level (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __cbccore_low_Device__ */
