/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __cbccore_low_Motor__
#define __cbccore_low_Motor__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_cbccore_low_Motor_motor (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_clear_1motor_1position_1counter (JNIEnv *env, jobject, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_move_1at_1velocity (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_mav (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_move_1to_1position (JNIEnv *env, jobject, jint, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_mtp (JNIEnv *env, jobject, jint, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_move_1relative_1position (JNIEnv *env, jobject, jint, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_mrp (JNIEnv *env, jobject, jint, jint, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Motor_set_1pid_1gains (JNIEnv *env, jobject, jint, jint, jint, jint, jint, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_freeze (JNIEnv *env, jobject, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_get_1motor_1done (JNIEnv *env, jobject, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_get_1motor_1position_1counter (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Motor_block_1motor_1done (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Motor_bmd (JNIEnv *env, jobject, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_setpwm (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Motor_getpwm (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Motor_fd (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Motor_bk (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Motor_off (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_cbccore_low_Motor_ao (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __cbccore_low_Motor__ */
