/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __cbccore_low_Input__
#define __cbccore_low_Input__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_cbccore_low_Input_up_1button (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Input_down_1button (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Input_left_1button (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Input_right_1button (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Input_a_1button (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Input_b_1button (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Input_black_1button (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __cbccore_low_Input__ */
