/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __cbccore_low_Display__
#define __cbccore_low_Display__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_cbccore_low_Display_display_1clear (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Display_cbc_1display_1clear (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __cbccore_low_Display__ */
