/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbccore_low_Create */

#ifndef _Included_cbccore_low_Create
#define _Included_cbccore_low_Create
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbccore_low_Create
 * Method:    create_connect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1connect
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1disconnect
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1start
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_passive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1passive
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_safe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1safe
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_full
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1full
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_spot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spot
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_cover
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1cover
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_demo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1demo
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_cover_dock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1cover_1dock
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_mode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1mode
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_sensor_update
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1sensor_1update
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_wall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1wall
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_buttons
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1buttons
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_bumpdrop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1bumpdrop
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_cliffs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1cliffs
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_angle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1angle
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_distance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1distance
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_velocity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1velocity
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_read_IR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1read_1IR
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_overcurrents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1overcurrents
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_battery_charge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1battery_1charge
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_cargo_bay_inputs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1cargo_1bay_1inputs
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1stop
  (JNIEnv *, jobject);

/*
 * Class:     cbccore_low_Create
 * Method:    create_drive
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_drive_straight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive_1straight
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_spin_CW
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spin_1CW
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_spin_CCW
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1spin_1CCW
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_drive_direct
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1drive_1direct
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_spin_block
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1spin_1block
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_advance_led
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1advance_1led
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_play_led
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1play_1led
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_power_led
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1power_1led
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_digital_output
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1digital_1output
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_pwm_low_side_drivers
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1pwm_1low_1side_1drivers
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_low_side_drivers
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1low_1side_1drivers
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_load_song
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1load_1song
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_play_song
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1play_1song
  (JNIEnv *, jobject, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_read_block
 * Signature: ([CI)I
 */
JNIEXPORT jint JNICALL Java_cbccore_low_Create_create_1read_1block
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     cbccore_low_Create
 * Method:    create_write_byte
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1write_1byte
  (JNIEnv *, jobject, jchar);

/*
 * Class:     cbccore_low_Create
 * Method:    create_clear_serial_buffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbccore_low_Create_create_1clear_1serial_1buffer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
