/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __cbccore_low_Camera__
#define __cbccore_low_Camera__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_cbccore_low_Camera_track_1init (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1is_1new_1data_1available (JNIEnv *env, jobject);
JNIEXPORT void JNICALL Java_cbccore_low_Camera_track_1update (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1get_1frame (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1count (JNIEnv *env, jobject, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1size (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1x (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1y (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1confidence (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1bbox_1left (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1bbox_1right (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1bbox_1top (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1bbox_1bottom (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1bbox_1width (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1bbox_1height (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jfloat JNICALL Java_cbccore_low_Camera_track_1angle (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1major_1axis (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1minor_1axis (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1capture_1time (JNIEnv *env, jobject);
JNIEXPORT jint JNICALL Java_cbccore_low_Camera_track_1previous_1capture_1time (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __cbccore_low_Camera__ */
